# colors={'red',"green",'blue'}
# print(colors)
# colors.add("yelow")
# print(colors)
# colors.remove("red")
# print(colors)
# colors.discard('red')
# print(colors)
# colors.discard("green")
# print(colors)
# colors.clear()
# print(colors)
# q=set()
# print(q)
a={1,2,3,4,5,6,7}
b={4,5,6,7,8,9,10}
c=a.copy()
print(c)
print(b)
u=a.union(b)
print(f'union {u}')
i=a.intersection(b)
print(F'intersection {i}')
d1=a.difference(b)
print(f"difference a: {d1}")
d2=b.difference(a)
print(f"difference b: {d2}")
q=a.union(b).difference(a.intersection(b))
print(q)
